### ISSUE TITLE
perl: warning: Setting locale failed. 

### ISSUE THREAD

**Issue by web-differently12** [christensenjairus/ClusterCreator#8]
helo thanks you for this project 
Please i have this error in create_template.sh

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
unable to parse directory volume name 'vm-9000-disk-0'
root@192.168.1.1's password:

**Comment by christensenjairus** [comment]
The perl warning is something that debian proxmox has by default. This is a warning on your host, which I'm hesitant to fix in the script because it's not a problem that ClusterCreator makes. I usually fix it when I first install proxmox. 

I usually do something like this for perl

```bash
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
locale-gen en_US.UTF-8
dpkg-reconfigure locales 
# then use en_US.UTF-8 for both options presented (just hit tab/enter)
```
Then append this to the `~/.bashrc` file
```bash
export LANGUAGE="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
```

***

This is separate from the real problem you're seeing, which is that file-based storage for VM disks need to be imported differently.

https://forum.proxmox.com/threads/unable-to-parse-directory-volume-name-vm-777-disk-0.116996/#post-506240

I get the same error using my local filesystem as the PROXMOX_DATASTORE. I'll fix this right now.

**Comment by christensenjairus** [comment]
@web-differently12 Please let me know if there are any other issues you run into. The project is still new and there are many edge cases I haven't tested for. I'll do my best to quickly fix anything you find.

Keep the issues and feature requests coming 😄

**Comment by web-differently12** [comment]
thanks you for your replay
